name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  cloud_firestore: ^6.1.0
  curved_navigation_bar: ^1.0.6
  
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  firebase_storage: ^13.0.4
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
      
  flutter_tts: ^4.2.3
  google_fonts: ^6.3.2
  google_maps_flutter: ^2.13.1
  http: ^1.5.0
  image_picker: ^1.2.1
  path: ^1.9.1
  pay: ^3.2.1
  permission_handler: ^12.0.1
  razorpay_flutter: ^1.4.0
  vector_math: ^2.1.4
  webview_flutter: ^4.0.1
 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/gpay.json
